@echo off
:: ============================================================
:: AIOPS-WINDOWS.BAT -- Windows Host Setup for AIOPS Stack
:: Quantocos AI Labs -- v3.0.0
::
:: Run as Administrator. Run once after aiops.sh completes.
:: Re-run after every Windows reboot to refresh WSL IP.
::
:: What this does:
::   1. Asks for your .local domain name
::   2. Sets up PowerShell execution policy
::   3. Creates the port proxy PowerShell script
::   4. Registers it as a Task Scheduler boot task (auto-run)
::   5. Runs it immediately so LAN access works right now
::   6. Shows all your service URLs
:: ============================================================

title AIOPS Windows Setup
color 0A

echo.
echo    ___   ___ ___  ___  ___
echo   / _ ^| |_ _/ _ \^| _ \/ __^|
echo  ^/ _ ^\ ^| ^| ^(_^) ^|  _/\__ \
echo /_/ \_\___\___/_^|_^|  ^|___/
echo.
echo  Windows Host Setup -- v3.0.0
echo  Quantocos AI Labs
echo.
echo ============================================================
echo.

:: Check for admin
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] This script must be run as Administrator.
    echo.
    echo Right-click aiops-windows.bat and select "Run as administrator"
    echo.
    pause
    exit /b 1
)

echo [OK] Running as Administrator
echo.

:: ============================================================
:: STEP 1 -- Domain name
:: ============================================================

echo ------------------------------------------------------------
echo  STEP 1 of 4 -- Your Local Domain Name
echo ------------------------------------------------------------
echo.
echo  This must match what you entered in aiops.sh
echo  Example: if you typed "myrig" in aiops.sh, type "myrig" here
echo  Default (press Enter): aiops
echo.
set /p DOMAIN_INPUT="  Enter domain name (without .local): "

if "%DOMAIN_INPUT%"=="" (
    set LOCAL_HOSTNAME=aiops
) else (
    set LOCAL_HOSTNAME=%DOMAIN_INPUT%
)
set LOCAL_DOMAIN=%LOCAL_HOSTNAME%.local

echo.
echo  [OK] Domain: %LOCAL_DOMAIN%
echo.

:: ============================================================
:: STEP 2 -- Create autostart folder and PowerShell script
:: ============================================================

echo ------------------------------------------------------------
echo  STEP 2 of 4 -- Creating Port Proxy Script
echo ------------------------------------------------------------
echo.

set AUTOSTART_DIR=C:\autostart
set PS_SCRIPT=%AUTOSTART_DIR%\wsl-portproxy.ps1

if not exist "%AUTOSTART_DIR%" (
    mkdir "%AUTOSTART_DIR%"
    echo  [OK] Created: %AUTOSTART_DIR%
)

:: Write the PowerShell port proxy script
:: This detects the WSL IP on every run -- handles IP changes on reboot
(
echo # ============================================================
echo # WSL-PORTPROXY.PS1 -- Auto Port Forwarding for WSL2
echo # Generated by aiops-windows.bat
echo # Domain: %LOCAL_DOMAIN%
echo # ============================================================
echo.
echo # Get current WSL IP
echo $wslIP = ^(wsl hostname -I^).Trim^(^).Split^(^)[0]
echo.
echo if ^(-not $wslIP^) {
echo     Write-Host "[ERROR] Could not get WSL IP. Start WSL first." -ForegroundColor Red
echo     exit 1
echo }
echo.
echo Write-Host "[INFO] WSL IP: $wslIP" -ForegroundColor Cyan
echo.
echo # Ports to forward -- add new services here as you install them
echo $ports = @^(
echo     80,      # Caddy -- all services via reverse proxy
echo     443,     # HTTPS ^(future^)
echo     8080,    # OpenWebUI direct
echo     5678,    # n8n direct
echo     6333,    # Qdrant direct
echo     8501,    # CrewAI Studio direct
echo     11434,   # Ollama API
echo     19999,   # Netdata monitoring
echo     3000,    # Twenty CRM
echo     9000,    # Listmonk email
echo     3100,    # Chatwoot inbox
echo     3002     # Cal.com booking
echo ^)
echo.
echo # Clear existing rules
echo Write-Host "[INFO] Resetting portproxy rules..." -ForegroundColor Yellow
echo netsh interface portproxy reset ^| Out-Null
echo.
echo # Add new rules
echo foreach ^($port in $ports^) {
echo     netsh interface portproxy add v4tov4 ``
echo         listenaddress=0.0.0.0 ``
echo         listenport=$port ``
echo         connectaddress=$wslIP ``
echo         connectport=$port ^| Out-Null
echo     Write-Host "  [OK] :$port -> $wslIP`:$port" -ForegroundColor Green
echo }
echo.
echo # Allow firewall rules for these ports
echo foreach ^($port in $ports^) {
echo     netsh advfirewall firewall delete rule name="AIOPS-$port" ^| Out-Null 2^>^&1
echo     netsh advfirewall firewall add rule ``
echo         name="AIOPS-$port" ``
echo         dir=in ``
echo         action=allow ``
echo         protocol=TCP ``
echo         localport=$port ^| Out-Null
echo }
echo.
echo # Get Windows LAN IP
echo $lanIP = ^(Get-NetIPAddress -AddressFamily IPv4 ^| Where-Object {
echo     $_.InterfaceAlias -notlike '*Loopback*' -and
echo     $_.InterfaceAlias -notlike '*WSL*' -and
echo     $_.IPAddress -notlike '169.*'
echo } ^| Select-Object -First 1^).IPAddress
echo.
echo Write-Host "" -ForegroundColor Green
echo Write-Host "[OK] Port forwarding active" -ForegroundColor Green
echo Write-Host "     LAN IP:  $lanIP" -ForegroundColor Cyan
echo Write-Host "     WSL IP:  $wslIP" -ForegroundColor Cyan
echo Write-Host "     Domain:  %LOCAL_DOMAIN%" -ForegroundColor Cyan
echo Write-Host "" -ForegroundColor Green
echo Write-Host "  Services now available on LAN:" -ForegroundColor White
echo Write-Host "    http://%LOCAL_DOMAIN%           OpenWebUI" -ForegroundColor White
echo Write-Host "    http://%LOCAL_DOMAIN%/n8n       n8n workflows" -ForegroundColor White
echo Write-Host "    http://%LOCAL_DOMAIN%/agents    CrewAI Studio" -ForegroundColor White
echo Write-Host "    http://%LOCAL_DOMAIN%/qdrant    Qdrant" -ForegroundColor White
echo Write-Host "    http://%LOCAL_DOMAIN%/ollama    Ollama API" -ForegroundColor White
echo Write-Host "" -ForegroundColor Green
) > "%PS_SCRIPT%"

echo  [OK] Port proxy script: %PS_SCRIPT%
echo.

:: ============================================================
:: STEP 3 -- Set execution policy + register Task Scheduler
:: ============================================================

echo ------------------------------------------------------------
echo  STEP 3 of 4 -- Registering Boot Task
echo ------------------------------------------------------------
echo.

:: Allow running PS scripts
powershell -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force" >nul 2>&1
echo  [OK] PowerShell execution policy set

:: Remove old task if it exists
schtasks /delete /tn "AIOPS-PortProxy" /f >nul 2>&1

:: Register new Task Scheduler task (runs at startup as SYSTEM)
schtasks /create ^
    /tn "AIOPS-PortProxy" ^
    /tr "powershell.exe -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File \"%PS_SCRIPT%\"" ^
    /sc ONSTART ^
    /ru SYSTEM ^
    /rl HIGHEST ^
    /f >nul 2>&1

if %errorlevel% equ 0 (
    echo  [OK] Boot task registered: AIOPS-PortProxy
    echo  [OK] Port proxy runs automatically on every Windows reboot
) else (
    echo  [!] Task registration failed -- run the PS script manually after reboot
)
echo.

:: ============================================================
:: STEP 4 -- Run port proxy now
:: ============================================================

echo ------------------------------------------------------------
echo  STEP 4 of 4 -- Activating Port Forwarding Now
echo ------------------------------------------------------------
echo.

powershell -ExecutionPolicy Bypass -File "%PS_SCRIPT%"

:: ============================================================
:: DONE
:: ============================================================

echo.
echo ============================================================
echo  AIOPS WINDOWS SETUP -- COMPLETE
echo ============================================================
echo.
echo  What was configured:
echo    [OK] Port proxy script:  %PS_SCRIPT%
echo    [OK] Boot task:          AIOPS-PortProxy (runs at startup)
echo    [OK] Execution policy:   RemoteSigned
echo    [OK] Firewall rules:     Added for all AIOPS ports
echo    [OK] Port forwarding:    Active now
echo.
echo  Your services (from any device on the LAN):
echo    http://%LOCAL_DOMAIN%           -^> OpenWebUI
echo    http://%LOCAL_DOMAIN%/n8n       -^> n8n Workflows
echo    http://%LOCAL_DOMAIN%/agents    -^> CrewAI Studio
echo    http://%LOCAL_DOMAIN%/qdrant    -^> Qdrant Dashboard
echo    http://%LOCAL_DOMAIN%/ollama    -^> Ollama API
echo.
echo  After every Windows reboot:
echo    Port proxy runs automatically. No action needed.
echo.
echo  If WSL IP changes and services stop working:
echo    Just run this .bat file again.
echo.
echo ============================================================
echo.
pause
